[package]
name = "api"
version = "0.0.1"
authors = ["Srimanta Barua <srimanta.barua1@gmail.com>"]
edition = "2018"

[dependencies]
httparse = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
